name: Release
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install node
        uses: actions/setup-node@v1
      
      - run: npm install yarn

      - name: Run Makefile
        run: make all
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v1
        with:
          name: dialect-chrome-extension
          path: dialect-chrome-extension.zip
      - name: Determine Release version
        run: |
          export RELEASE_VERSION=$(sed 's/.*"version": "\(.*\)".*/\1/;t;d' ./manifest.json)
          echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION"
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          artifact: "dialect-chrome-extension.zip"